### ISSUE TITLE
Remove double quotes and add regex

### ISSUE THREAD

**Issue by faisalrathore93** [0xsha/GoLinkFinder#2]
Hey, Hi!
this is a great tool. I would like to request some modifications. please remove the double quotes from the output and regex feature like -i in linkfinder. like if i want to fetch endpoints with /api/* only then I can do someting like this golinkfinder -d site.com -i ^/api/ -o apiendpoints.txt

Thanks!

**Comment by 0xsha** [comment]
Hi,  thanks for your report

double quote issue should be fixed now and you can just pipe this to grep if you are on nix* 


```
go run GoLinkFinder.go -d github.com | grep api
https://api.github.com/_private/browser/stats
https://api.github.com/_private/browser/errors
https://api.github.com/_private/browser/optimizely_client/errors
```
