### ISSUE TITLE
Error in "go build" command

### ISSUE THREAD

**Issue by learn-alam** [0xsha/GoLinkFinder#4]
hey...
when i run "go build GoLinkFinder, i got below error...

GoLinkFinder.go:18:2: cannot find package "github.com/PuerkitoBio/goquery" in any of:
	/usr/lib/go-1.10/src/github.com/PuerkitoBio/goquery (from $GOROOT)
	/home/alam/go/src/github.com/PuerkitoBio/goquery (from $GOPATH)
GoLinkFinder.go:19:2: cannot find package "github.com/akamensky/argparse" in any of:
	/usr/lib/go-1.10/src/github.com/akamensky/argparse (from $GOROOT)
	/home/alam/go/src/github.com/akamensky/argparse (from $GOPATH)
GoLinkFinder.go:20:2: cannot find package "github.com/tomnomnom/gahttp" in any of:
	/usr/lib/go-1.10/src/github.com/tomnomnom/gahttp (from $GOROOT)
	/home/alam/go/src/github.com/tomnomnom/gahttp (from $GOPATH)

**Comment by 0xsha** [comment]
Hi
you have to go get it's decencies  argparse , goquery , gahttp .
