### ISSUE TITLE
error in "go get" command

### ISSUE THREAD

**Issue by learn-alam** [0xsha/GoLinkFinder#5]
hi.....
first thanks for your reply.
As you told me to run go get command, i did it and got following error....
please help me again.
Thanks.

alam@learn:~/GoLinkFinder$ go get
# _/home/alam/GoLinkFinder
./GoLinkFinder.go:83:13: undefined: strings.ReplaceAll
./GoLinkFinder.go:84:13: undefined: strings.ReplaceAll
./GoLinkFinder.go:197:11: undefined: strings.ReplaceAll
./GoLinkFinder.go:198:11: undefined: strings.ReplaceAll
./GoLinkFinder.go:213:12: undefined: strings.ReplaceAll
./GoLinkFinder.go:214:12: undefined: strings.ReplaceAll

**Comment by BugHunter001** [comment]
$ go build

GoLinkFinder.go:19:2: cannot find package "github.com/akamensky/argparse" in any of:
        /usr/local/go/src/github.com/akamensky/argparse (from $GOROOT)
        /root/go/src/github.com/akamensky/argparse (from $GOPATH)
GoLinkFinder.go:20:2: cannot find package "github.com/tomnomnom/gahttp" in any of:
        /usr/local/go/src/github.com/tomnomnom/gahttp (from $GOROOT)
        /root/go/src/github.com/tomnomnom/gahttp (from $GOPATH)

i am trying a lo but i am still getting error

**Comment by pczajkowski** [comment]
> hi.....
> first thanks for your reply.
> As you told me to run go get command, i did it and got following error....
> please help me again.
> Thanks.
> 
> alam@learn:~/GoLinkFinder$ go get
> # _/home/alam/GoLinkFinder
> 
> ./GoLinkFinder.go:83:13: undefined: strings.ReplaceAll
> ./GoLinkFinder.go:84:13: undefined: strings.ReplaceAll
> ./GoLinkFinder.go:197:11: undefined: strings.ReplaceAll
> ./GoLinkFinder.go:198:11: undefined: strings.ReplaceAll
> ./GoLinkFinder.go:213:12: undefined: strings.ReplaceAll
> ./GoLinkFinder.go:214:12: undefined: strings.ReplaceAll

Please provide output of `go version` as `strings.ReplaceAll` has been introduced in Go at version 1.12.

**Comment by 0xsha** [comment]
you need to full go get  like github.com/akamensky/argparse and so on .  for replaceAll update your Golang as nicely suggested by @pczajkowski 

Feel free to re-open if still have issues.
