### ISSUE TITLE
runtime error when running with rush

### ISSUE THREAD

**Issue by ranjit-git** [0xsha/GoLinkFinder#6]
when running your tool with https://github.com/shenwei356/rush ,it gives runtime error

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x68ea65]

goroutine 1 [running]:
main.extractJSLinksFromHTML(0x7ffe110cb26e, 0x5d, 0x0, 0x0, 0x0)
	/home/bug/Desktop/GoLinkFinder/GoLinkFinder.go:148 +0x95
main.main()
	/home/bug/Desktop/GoLinkFinder/GoLinkFinder.go:192 +0x297
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x68ea65]

goroutine 1 [running]:
main.extractJSLinksFromHTML(0x7ffc541342a2, 0x29, 0x0, 0x0, 0x0)
	/home/bug/Desktop/GoLinkFinder/GoLinkFinder.go:148 +0x95

**Comment by a6thmfsin** [comment]
got same idk why it all of a sudden stopped working, tried reinstalling aswell

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x666f8f]

goroutine 1 [running]:
main.extractJSLinksFromHTML({0x7ffd9291923f, 0x4e})
        /home/greyhound/go/pkg/mod/github.com/0xsha/!go!link!finder@v0.0.0-20220719102359-604f88a2eb4f/GoLinkFinder.go:148 +0x6f
main.main()
        /home/greyhound/go/pkg/mod/github.com/0xsha/!go!link!finder@v0.0.0-20220719102359-604f88a2eb4f/GoLinkFinder.go:192 +0x228

**Comment by Frog-man-sec** [comment]
### Getting same issue. don't know why

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x6736de]

goroutine 1 [running]:
main.extractJSLinksFromHTML({0x7fff27cfd136, 0x15})
        /home/user/htools/GoLinkFinder/GoLinkFinder.go:151 +0x5e
main.main()
        /home/user/htools/GoLinkFinder/GoLinkFinder.go:205 +0x1c5

```

**Comment by Sakuragi-Hanamichii** [comment]
same issue

**Comment by noob6t5** [comment]
Hello there , I have done PR for this  . Can you check that once.
