### ISSUE TITLE
Error in go build

### ISSUE THREAD

**Issue by learn-alam** [0xsha/GoLinkFinder#7]
when i run go build command following command occurs ....

GoLinkFinder.go:18:2: cannot find package "github.com/PuerkitoBio/goquery" in any of:
	/usr/local/go/src/github.com/PuerkitoBio/goquery (from $GOROOT)
	/home/alam/go/src/github.com/PuerkitoBio/goquery (from $GOPATH)
GoLinkFinder.go:19:2: cannot find package "github.com/akamensky/argparse" in any of:
	/usr/local/go/src/github.com/akamensky/argparse (from $GOROOT)
	/home/alam/go/src/github.com/akamensky/argparse (from $GOPATH)
GoLinkFinder.go:20:2: cannot find package "github.com/tomnomnom/gahttp" in any of:
	/usr/local/go/src/github.com/tomnomnom/gahttp (from $GOROOT)
	/home/alam/go/src/github.com/tomnomnom/gahttp (from $GOPATH)

**Comment by p3n7a90n** [comment]
Hi ,
 
As the error says you have to download all the missing packages that this is project is currently using.Below is the list from your error :
https://github.com/PuerkitoBio/goquery
https://github.com/akamensky/argparse
https://github.com/tomnomnom/gahttp

You can manually go to your go directory and do a git clone or you can use go get cmd usually mentioned in every go language repo.

**Comment by learn-alam** [comment]
Thanks for help.
